# Form implementation generated from reading ui file 'ViewAddMember.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from helper.api_helper import view
import mysql.connector as mc

class Ui_ViewAddMember(object):
    def setupUi(self, ViewBook):
        ViewBook.setObjectName("ViewBook")
        ViewBook.resize(720, 441)
        self.layoutWidget = QtWidgets.QWidget(parent=ViewBook)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 10, 411, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.layoutWidget1 = QtWidgets.QWidget(parent=ViewBook)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 281, 421))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ID_lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ID_lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.ID_lineEdit_2.setFont(font)
        self.ID_lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color: #bcf0ff;\n"
"padding-left:10px;\n"
"}")
        self.ID_lineEdit_2.setObjectName("ID_lineEdit_2")
        self.verticalLayout_2.addWidget(self.ID_lineEdit_2)
        self.Name_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Name_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.Name_lineEdit.setFont(font)
        self.Name_lineEdit.setStyleSheet("QLineEdit{\n"
"padding-left:10px;\n"
"background-color: #bcf0ff;\n"
"}")
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.verticalLayout_2.addWidget(self.Name_lineEdit)
        self.Mobile_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Mobile_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.Mobile_lineEdit.setFont(font)
        self.Mobile_lineEdit.setStyleSheet("QLineEdit{\n"
"padding-left:10px;\n"
"background-color: #bcf0ff;\n"
"}")
        self.Mobile_lineEdit.setObjectName("Mobile_lineEdit")
        self.verticalLayout_2.addWidget(self.Mobile_lineEdit)
        self.Email_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Email_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.Email_lineEdit.setFont(font)
        self.Email_lineEdit.setStyleSheet("\n"
"QLineEdit{\n"
"background-color: #bcf0ff;\n"
"padding-left:10px;\n"
"}")
        self.Email_lineEdit.setObjectName("Email_lineEdit")
        self.verticalLayout_2.addWidget(self.Email_lineEdit)
        self.InsertBook_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.InsertBook_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InsertBook_pushButton.setFont(font)
        self.InsertBook_pushButton.setStyleSheet("QPushButton{\n"
"background-color: #bcf0ff;}")
        self.InsertBook_pushButton.setObjectName("InsertBook_pushButton")
        self.verticalLayout_2.addWidget(self.InsertBook_pushButton)
        self.DeleteMember_pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.DeleteMember_pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteMember_pushButton_2.setFont(font)
        self.DeleteMember_pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: #bcf0ff;}")
        self.DeleteMember_pushButton_2.setObjectName("DeleteMember_pushButton_2")
        self.verticalLayout_2.addWidget(self.DeleteMember_pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.Result_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Result_label.sizePolicy().hasHeightForWidth())
        self.Result_label.setSizePolicy(sizePolicy)
        self.Result_label.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Result_label.setFont(font)
        self.Result_label.setStyleSheet("QLabel{background-color: #bcf0ff;padding-left:10px;}")
        self.Result_label.setText("")
        self.Result_label.setObjectName("Result_label")
        self.verticalLayout_2.addWidget(self.Result_label)

        self.retranslateUi(ViewBook)
        QtCore.QMetaObject.connectSlotsByName(ViewBook)
        self.InsertBook_pushButton.clicked.connect(self.insert_member)
        self.InsertBook_pushButton.clicked.connect(self.view_member)
        self.DeleteMember_pushButton_2.clicked.connect(self.delet_member)
        self.DeleteMember_pushButton_2.clicked.connect(self.view_member)
        
    def view_member(self):
        view(name_table="addmember",tableWidget=self.tableWidget)
    
#TODO : issue book ro be avialbel taghir bde bad member ro pak kone
    def delet_member(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="", database="library_system")
            mycursor = mydb.cursor()
            member_id = self.ID_lineEdit_2.text()
            if member_id != "" :
                query_delete = f"DELETE FROM addmember WHERE id = '{member_id}'"
                # query_delete = f"DELETE FROM addmember WHERE id = '{member_id}'"
                
                mycursor.execute(query_delete)
                self.Result_label.setText("Succesfuly Delete Member")
                self.Result_label.setStyleSheet("color:green;")
            else:
                self.Result_label.setText("Pls Give Me ID")
                self.Result_label.setStyleSheet("color:red;")
        except mc.Error as err:
            self.Result_label.setText("Failed to connect to db\n"+err.msg)
            self.Result_label.setStyleSheet("color:red")
                       
                
    def insert_member(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="", database="library_system")
            mycursor = mydb.cursor()
            member_id = self.ID_lineEdit_2.text()
            member_name = self.Name_lineEdit.text()
            member_mobile = self.Mobile_lineEdit.text()
            member_email = self.Email_lineEdit.text()
            if member_name == "" or member_id == "" or member_email == "" or member_mobile == "":
                self.Result_label.setText("Fields cannot be empty!")
                self.Result_label.setStyleSheet("color:red")
                return
                          
            query = "INSERT INTO addmember (id,name,mobile,email) VALUES (%s, %s, %s, %s)"
            Values = (member_id,member_name,member_mobile,member_email)
            
            mycursor.execute(query,Values)
            mydb.commit()
            self.Result_label.setText("Succesfuly added to Member")
            self.Result_label.setStyleSheet("color:green;")
        except mc.Error as err:
            self.Result_label.setText("Failed to connect to db\n"+err.msg)
            self.Result_label.setStyleSheet("color:red")

    def retranslateUi(self, ViewBook):
        _translate = QtCore.QCoreApplication.translate
        ViewBook.setWindowTitle(_translate("ViewBook", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ViewBook", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ViewBook", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ViewBook", "Mobile"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ViewBook", "Email"))
        self.view_member()
        self.ID_lineEdit_2.setPlaceholderText(_translate("ViewBook", "Enter ID Please"))
        self.Name_lineEdit.setPlaceholderText(_translate("ViewBook", "Enter Name Please"))
        self.Mobile_lineEdit.setPlaceholderText(_translate("ViewBook", "Enter Mobile Please"))
        self.Email_lineEdit.setPlaceholderText(_translate("ViewBook", "Enter Email Please"))
        self.InsertBook_pushButton.setText(_translate("ViewBook", "Insert Member"))
        self.DeleteMember_pushButton_2.setText(_translate("ViewBook", "Delete Member"))
