# Form implementation generated from reading ui file 'ViewAddBook.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from helper.api_helper import view
import mysql.connector as mc

class Ui_ViewAddBook(object):
    def setupUi(self, ViewBook):
        ViewBook.setObjectName("ViewBook")
        ViewBook.resize(903, 441)
        self.layoutWidget = QtWidgets.QWidget(parent=ViewBook)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 10, 541, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.layoutWidget1 = QtWidgets.QWidget(parent=ViewBook)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 331, 441))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Title_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.Title_lineEdit.setFont(font)
        self.Title_lineEdit.setStyleSheet("QLineEdit{\n"
"padding-left:10px;\n"
"background-color: #bcf0ff;\n"
"}")
        self.Title_lineEdit.setObjectName("Title_lineEdit")
        self.verticalLayout_2.addWidget(self.Title_lineEdit)
        self.ID_lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ID_lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.ID_lineEdit_2.setFont(font)
        self.ID_lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color: #bcf0ff;\n"
"padding-left:10px;\n"
"}")
        self.ID_lineEdit_2.setObjectName("ID_lineEdit_2")
        self.verticalLayout_2.addWidget(self.ID_lineEdit_2)
        self.Author_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Author_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.Author_lineEdit.setFont(font)
        self.Author_lineEdit.setStyleSheet("QLineEdit{\n"
"padding-left:10px;\n"
"background-color: #bcf0ff;\n"
"}")
        self.Author_lineEdit.setObjectName("Author_lineEdit")
        self.verticalLayout_2.addWidget(self.Author_lineEdit)
        self.Publisher_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Publisher_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.Publisher_lineEdit.setFont(font)
        self.Publisher_lineEdit.setStyleSheet("\n"
"QLineEdit{\n"
"background-color: #bcf0ff;\n"
"padding-left:10px;\n"
"}")
        self.Publisher_lineEdit.setObjectName("Publisher_lineEdit")
        self.verticalLayout_2.addWidget(self.Publisher_lineEdit)
        self.InsertBook_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.InsertBook_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InsertBook_pushButton.setFont(font)
        self.InsertBook_pushButton.setStyleSheet("QPushButton{\n"
"background-color: #bcf0ff;}")
        self.InsertBook_pushButton.setObjectName("InsertBook_pushButton")
        self.verticalLayout_2.addWidget(self.InsertBook_pushButton)
        self.DeleteBook_pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.DeleteBook_pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteBook_pushButton_2.setFont(font)
        self.DeleteBook_pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: #bcf0ff;}")
        self.DeleteBook_pushButton_2.setObjectName("DeleteBook_pushButton_2")
        self.verticalLayout_2.addWidget(self.DeleteBook_pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(329, 17, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.Result_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Result_label.sizePolicy().hasHeightForWidth())
        self.Result_label.setSizePolicy(sizePolicy)
        self.Result_label.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Result_label.setFont(font)
        self.Result_label.setStyleSheet("QLabel{background-color: #bcf0ff;padding-left:10px;}")
        self.Result_label.setText("")
        self.Result_label.setObjectName("Result_label")
        self.verticalLayout_2.addWidget(self.Result_label)
        self.retranslateUi(ViewBook)
        QtCore.QMetaObject.connectSlotsByName(ViewBook)
        self.InsertBook_pushButton.clicked.connect(self.insert_book)
        self.InsertBook_pushButton.clicked.connect(self.view_books)
        self.DeleteBook_pushButton_2.clicked.connect(self.delet_book)
        self.DeleteBook_pushButton_2.clicked.connect(self.view_books)
        
    def view_books(self):
        view(name_table="addbook",tableWidget=self.tableWidget)
    
    def delet_book(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="", database="library_system")
            mycursor = mydb.cursor()
            book_id = self.ID_lineEdit_2.text()
            book_title = self.Title_lineEdit.text()
            book_author = self.Author_lineEdit.text()
            book_publisher = self.Publisher_lineEdit.text()
            if book_id != "" and book_title == "" and book_author == "" and book_publisher == "":
                query_delete = f"DELETE FROM addbook WHERE id = '{book_id}'"
                mycursor.execute(query_delete)
                self.Result_label.setText("Succesfuly Delete Book")
                self.Result_label.setStyleSheet("color:green;")
        except mc.Error as err:
            self.Result_label.setText("Failed to connect to db\n"+err.msg)
            self.Result_label.setStyleSheet("color:red")
                       
                
    def insert_book(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="", database="library_system")
            mycursor = mydb.cursor()
            book_id = self.ID_lineEdit_2.text()
            book_title = self.Title_lineEdit.text()
            book_author = self.Author_lineEdit.text()
            book_publisher = self.Publisher_lineEdit.text()
            if book_id == "" or book_title == "" or book_author == "" or book_publisher == "":
                self.Result_label.setText("Fields cannot be empty!")
                self.Result_label.setStyleSheet("color:red")
                return
                          
            query = "INSERT INTO addbook (id,title,author,publisher) VALUES (%s, %s, %s, %s)"
            Values = (book_id,book_title,book_author,book_publisher)
            
            mycursor.execute(query,Values)
            mydb.commit()
            self.Result_label.setText("Succesfuly added to bookds")
            self.Result_label.setStyleSheet("color:green;")
        except mc.Error as err:
            self.Result_label.setText("Failed to connect to db\n"+err.msg)
            self.Result_label.setStyleSheet("color:red")
   
    def retranslateUi(self, ViewBook):
        _translate = QtCore.QCoreApplication.translate
        ViewBook.setWindowTitle(_translate("ViewBook", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ViewBook", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ViewBook", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ViewBook", "Author"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ViewBook", "Publisher"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ViewBook", "Available"))
        self.view_books()
        self.Title_lineEdit.setPlaceholderText(_translate("ViewBook", "Enter Title Please"))
        self.ID_lineEdit_2.setPlaceholderText(_translate("ViewBook", "Enter ID Please"))
        self.Author_lineEdit.setPlaceholderText(_translate("ViewBook", "Enter Author Please"))
        self.Publisher_lineEdit.setPlaceholderText(_translate("ViewBook", "Enter Publisher Please"))
        self.InsertBook_pushButton.setText(_translate("ViewBook", "Insert Book"))
        self.DeleteBook_pushButton_2.setText(_translate("ViewBook", "Delete Book"))